### ISSUE TITLE
Running Kibana kubernetes-elasticsearch-cluster

### ISSUE THREAD

**Issue by syz3r** [pires/kubernetes-elasticsearch-cluster#100]
Hi Pires,

Thanks for creating this project I was breaking my head trying to deploy elasticsearch on kubernetes. I was able to launch with 3 master 2 client and 3 data (stateful) very easily. I have also enabled x-pack plugin using env variables from docker-elasticsearch project. However I'm not able to add kibana to my cluster. I have created kibana.yaml and kibana-svc.yaml but not able to access it. Could you please help me with that. Also how can i reuse same LoadBalancer svc with different port number for kibana.

```YAML
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-kibana
  labels:
    component: elasticsearch
    role: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: kibana
    spec:
      containers:
      - name: es-kibana
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: docker.elastic.co/kibana/kibana:5.3.0
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name               
        - name: SERVER_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name            
        - name: ELASTICSEARCH_URL
          value: "http://CLIENTIP:9200"       
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "changeme"          
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
```
```YAML
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-kibana
  labels:
    component: elasticsearch
    role: kibana
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch
    role: kibana
  ports:
  - name: http
    port: 5601
    protocol: TCP
```
