### ISSUE TITLE
need to add PersistentVolume to make StatefulSet deployment work

### ISSUE THREAD

**Issue by bw2** [pires/kubernetes-elasticsearch-cluster#113]
Thanks for this really helpful repo. 

I just tried following StatefulSet deployment instructions (https://github.com/pires/kubernetes-elasticsearch-cluster/tree/master/stateful) but ended up with data pods that failed to initialize due to this error: 

`SchedulerPredicates failed due to PersistentVolumeClaim is not bound ...`

To get things working, I needed to first create a GKE PersistentDisk: 

`gcloud compute disks create  --zone <gke-zone>  --size 500G my-persistent-disk`

and then deploy a PersistentVolume:

`kubectl create -f es-persistent-volume.yaml`

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistent-disk
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-storage-class
  gcePersistentDisk:
    fsType: ext4
    pdName: my-persistent-disk
```
 Unless I'm missing something and this is a non-issue, I can submit a PR with this file.
