### ISSUE TITLE
Avoid cluster down on a configuration missmatch

### ISSUE THREAD

**Issue by deimosfr** [pires/kubernetes-elasticsearch-cluster#146]
Hi,

As explained in this PR (https://github.com/pires/docker-elasticsearch/pull/44), it would be great to have a safe guard and ensure each node has properly booted before restarting/starting another one. In a rolling restart case, this could be dramatic if any nodes are rolled out and no one could boot.

To avoid this I've proposed a script inside the docker container but this has been refused. So here is another proposal with a configmap:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: elasticsearch-configmap
data:
  postStart.sh: |-
    #!/bin/sh
    while [ $(netstat -auntpl | grep LISTEN | grep -c 9300) -eq 0 ] ; do
      echo "waiting port to be opened"
      sleep 5
      pidof java || exit 1
    done
    exit 0
```
Then in the statefulset, getting:
```yaml
...
   containers:
...
        lifecycle:
          postStart:
            exec:
              command: ["/elasticsearch/scripts/postStart.sh"]
...
        volumeMounts:
...
        - name: elasticsearch-configmap
          mountPath: /elasticsearch/scripts
      volumes:
...
        - name: elasticsearch-configmap
          configMap:
            name: elasticsearch-configmap
            defaultMode: 0775
```

What do you think ? I can make a PR if you agree with the idea.
