### ISSUE TITLE
[Feature/Support request] Nginx Ingress for Kibana

### ISSUE THREAD

**Issue by Unb9rn** [pires/kubernetes-elasticsearch-cluster#176]
Hello!
Maybe it is a good idea to add nginx ingress to kibana?
Something like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-kibana-basic-auth
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: http-auth
    nginx.ingress.kubernetes.io/auth-realm: "Password or GTFO"
spec:
  rules:
  - http:
      paths:
      - path: /kibana
        backend:
          serviceName: kibana
          servicePort: 80
```
But I am having a hard time trying to add this while simultaneously retain ability to access Kibana through API Server proxy. 
What basepath should I specify?

**Comment by pires** [comment]
That would require depending on nginx ingress controller so I don't think it would be wise to enforce that.

**Comment by Unb9rn** [comment]
Of course! I thought to offer it as an option.

**Comment by pires** [comment]
Sure, open the PR.

**Comment by pires** [comment]
Closing due to inactivity. Will re-open if a PR is open to address this.

**Comment by GitShaffi** [comment]
@Unb9rn Were you able to proxy kibana behind ingress?? Any work arounds?

**Comment by GitShaffi** [comment]
@Unb9rn 
However I am not able to get this to work.
```
spec:
  rules:
  - http:
      paths:
      - path: /kibana
        backend:
          serviceName: kibana
          servicePort: 80
```

But I am able to get it working, if I proxy it at root **'/'** .

**Comment by Unb9rn** [comment]
@GitShaffi I am using it with basic auth with htpasswd stored in secret, but you may be able to adapt it for you. Also, I am serving it as a subdomain in /
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-kibana-basic-auth
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: http-auth
    ingress.kubernetes.io/auth-realm: "Password, tits or GTFO"
spec:
  tls:
  - hosts:
    - kibana.example.com
    secretName: tlssecret
  rules:
  - host: kibana.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 80
```
