### ISSUE TITLE
Add anti-affinity to avoid scheduling multiple ES pods onto the same nodes

### ISSUE THREAD

**Issue by rocketraman** [pires/kubernetes-elasticsearch-cluster#191]
Specs, especially master and data deployments and stateful sets, should probably include a pod anti-affinity configuration, to avoid scheduling multiple pods onto the same nodes. For example:

```
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "component"
                    operator: In
                    values:
                    - "elasticsearch"
                  - key: "role"
                    operator: In
                    values:
                    - "data"
              topologyKey: "kubernetes.io/hostname"
```
