### ISSUE TITLE
unknown field "hostPath"

### ISSUE THREAD

**Issue by SHUFIL** [pires/kubernetes-elasticsearch-cluster#206]
i getting this issue , only one change in yaml file , what i have used in yaml instead of 
```
volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      storageClassName: standard
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 12Gi 
```
i have used 
```
        volumeMounts:
        - name: storage
          mountPath: /es
        volumes:
      - name: storage
        hostPath:
          path: /es
```
but its getting error .
