### ISSUE TITLE
Stability and health-checks via livenessProbe

### ISSUE THREAD

**Issue by andrewmclagan** [pires/kubernetes-elasticsearch-cluster#76]
Not so much an issue (apologies). More as a community resource.

Seeking advice and best practices for `livenessProbe` health checks on our ES nodes.

We are thinking the following HTTP health-checks would be conservative and allow for high load situations. My concerns / questions are:

* Will a destroyed/restarted node have adverse effects on a cluster setup as per this repo?
* Will multiple destroyed/restarted masters have any serious side effects?
* What are others doing for restart/health-checks? Anything? 
* Would it be good at a minimum to have a `livenessProbe` on master nodes, where data persistence is not an issue?

### es-client
```
livenessProbe:
  initialDelaySeconds: 25
  timeoutSeconds: 5
  periodSeconds: 8
  successThreshold: 5
  failureThreshold: 2
  httpGet:
    path: /
    port: 9200
```

### es-data, es-master
```
livenessProbe:
  initialDelaySeconds: 25
  timeoutSeconds: 5
  periodSeconds: 8
  successThreshold: 5
  failureThreshold: 2
  tcpSocket:
    port: 9300 
```
